#!/usr/bin/env pwsh
<# 
.SYNOPSIS 
    This file is generated by Terraform
    https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file
    https://www.terraform.io/language/functions/templatefile
#> 

$keyVaultName = "${keyVaultName}"
$resourceGroup = "${resourceGroup}"
$subscriptionId = "${subscriptionId}"

Write-Host "`nTesting ARM control plane access to Key Vault '${keyVaultName}' in resource group '${resourceGroup}' (subscription '${subscriptionId}')"
az keyvault show -n ${keyVaultName} -g ${resourceGroup} --subscription ${subscriptionId} -o table

Write-Host "`nTesting data plane access to Key Vault '${keyVaultName}' in resource group '${resourceGroup}' (subscription '${subscriptionId}')"
az keyvault secret list --vault-name ${keyVaultName} --subscription ${subscriptionId} -o table